baseurl = "https://mehdibaha.com/"
languageCode = "en-US"
title = "Mehdi Baha"
googleAnalytics = "UA-106331831-1"
theme = "hugo-sustain"
enableRobotsTXT = true

[permalinks]
  post = "/:slug"

[params]
  avatar = "profile.jpeg"
  author = "Mehdi Baha"
  description = "Software Engineer and Tech enthusiast"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "mehdibaha"
  Email         = "elmehdi dot baha at gmail"
  Twitter       = "@elmehdi_baha"
  LinkedIn      = "mehdibaha"
  Stackoverflow = "users/2352011/mehdi"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 1
  url = "/blog/"
[[menu.main]]
  name = "projects"
  weight = 2
  url = "/projects/"
[[menu.main]]
  name = "twitter"
  weight = 5
  url = "https://twitter.com/elmehdi_baha"
  pre = "fab fa-twitter"
